site_name: "CV Artur Mudrykh"
theme:
  name: "material"

nav:
  - Home: index.md
  - Download: Download.md

extra_javascript:
  - js/custom.js

markdown_extensions:
  - attr_list

use_directory_urls: false

plugins:
  - with-pdf:
      output_path: ../Artur_Mudrykh_CV.pdf