site_name: "CV Artur Mudrykh"
theme:
  name: "material"

nav:
  - Resume (EN): index.md
  - Резюме (RU): index_ru.md
  - Download / Загрузка: Download.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js
  - js/custom.js

markdown_extensions:
  - attr_list

use_directory_urls: false
