name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Build site with PDF generation
        run: mkdocs build

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
